#!/bin/bash

set -e

if [[ -z ${1:-} ]]; then
	echo "E: update-initramfs did not pass a version number" >&2
	exit 1
else
	version="$1"
fi

if [[ -z ${2:-} ]]; then
	echo "E: update-initramfs did not pass an initramfs path" >&2
	exit 1
else
	initramfs="$2"
fi

if [ ! -f "/etc/cmdline" ]; then
	echo "E: cmdline file /etc/cmdline doesn't exist."
	exit 2
fi

if [ ! -d "/etc/efi-keys" ]; then
	echo "E: EFI Secure Boot Key folder /etc/efi-keys doesn't exist."
	exit 3
fi

if ! command -v objcopy >/dev/null 2>&1; then
	echo "E: objcopy command doesn't exist, install binutils."
	exit 4
fi

if ! command -v sbsign >/dev/null 2>&1; then
	echo "E: sbsign command doesn't exist, install sbsigntool."
	exit 5
fi

align="$(objdump -p /usr/lib/systemd/boot/efi/linuxx64.efi.stub | awk '{ if ($1 == "SectionAlignment"){print $2} }')"
align=$((16#$align))
osrel_offs="$(objdump -h "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" | awk 'NF==7 {size=strtonum("0x"$3); offset=strtonum("0x"$4)} END {print size + offset}')"
osrel_offs=$((osrel_offs + "$align" - osrel_offs % "$align"))
cmdline_offs=$((osrel_offs + $(stat -Lc%s "/usr/lib/os-release")))
cmdline_offs=$((cmdline_offs + "$align" - cmdline_offs % "$align"))
splash_offs=$((cmdline_offs + $(stat -Lc%s "/etc/cmdline")))
splash_offs=$((splash_offs + "$align" - splash_offs % "$align"))
initrd_offs=$((splash_offs + $(stat -Lc%s "/dev/null")))
initrd_offs=$((initrd_offs + "$align" - initrd_offs % "$align"))
linux_offs=$((initrd_offs + $(stat -Lc%s "${initramfs}")))
linux_offs=$((linux_offs + "$align" - linux_offs % "$align"))

objcopy \
    --add-section .osrel="/usr/lib/os-release" --change-section-vma .osrel=$(printf 0x%x $osrel_offs) \
    --add-section .cmdline="/etc/cmdline" --change-section-vma .cmdline=$(printf 0x%x $cmdline_offs) \
    --add-section .splash="/dev/null" --change-section-vma .splash=$(printf 0x%x $splash_offs) \
    --add-section .initrd="${initramfs}" --change-section-vma .initrd=$(printf 0x%x $initrd_offs) \
    --add-section .linux="/boot/vmlinuz-${version}" --change-section-vma .linux=$(printf 0x%x $linux_offs) \
    "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" "/tmp/unified-image.efi"

sbsign --key /etc/efi-keys/db.key --cert /etc/efi-keys/db.crt --output /tmp/linux-signed.efi /tmp/unified-image.efi
mv /tmp/unified-image.efi /boot
mv /tmp/linux-signed.efi /boot/efi/EFI/Linux
