#!/bin/bash

set -e

if [[ -z ${1:-} ]]; then
	echo "E: update-initramfs did not pass a version number" >&2
	exit 1
else
	version="$1"
fi

if [[ -z ${2:-} ]]; then
	echo "E: update-initramfs did not pass an initramfs path" >&2
	exit 1
else
	initramfs="$2"
fi

if [ ! -f "/etc/cmdline" ]; then
	echo "E: cmdline file /etc/cmdline doesn't exist."
	exit 2
fi

if [ ! -d "/etc/efi-keys" ]; then
	echo "E: EFI Secure Boot Key folder /etc/efi-keys doesn't exist."
	exit 3
fi

if ! command -v objcopy >/dev/null 2>&1; then
	echo "E: objcopy command doesn't exist, install binutils."
	exit 4
fi

if ! command -v sbsign >/dev/null 2>&1; then
	echo "E: sbsign command doesn't exist, install sbsigntool."
	exit 5
fi

rm -f /boot/unified-image.efi
rm -f /boot/efi/EFI/Linux/linux-signed.efi

objcopy \
    --add-section .osrel="/usr/lib/os-release" --change-section-vma .osrel=0x20000 \
    --add-section .cmdline="/etc/cmdline" --change-section-vma .cmdline=0x30000 \
    --add-section .splash="/dev/null" --change-section-vma .splash=0x40000 \
    --add-section .linux="/boot/vmlinuz-${version}" --change-section-vma .linux=0x2000000 \
    --add-section .initrd="${initramfs}" --change-section-vma .initrd=0x3000000 \
    "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" "/boot/unified-image.efi"

sbsign --key /etc/efi-keys/db.key --cert /etc/efi-keys/db.crt --output /boot/efi/EFI/Linux/linux-signed.efi /boot/unified-image.efi
